### ISSUE TITLE
Use of Stack-Id in master Tag, issue with multiple deployments

### ISSUE THREAD

**Issue by amolari** [F5Networks/f5-cloud-libs-aws#4]
The CF StackId must be unique in a region. We have a use-case where multiple CF stacks will be created in the same region. Issue: the master instance has a tag key=<stackid>-master, value=true.
We cannot use that tag in our dynamic Ansible inventory, because aws cli describe-instances filter doesn't support wildcard/regex in the Tag key (but only in the value). As this master tag is a pure local information (scope: cluster), please give it a key name which has only a local relevance => static/same for all deployments.

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with your use case. I've created internal ID ESECLDTPLT-1999 for this enhancement.

**Comment by amolari** [comment]
Having the tag set to `<deploymentname>-stack-master=true`
one can match the instance in Ansible inventory using the filter `tag-key=*-stack-master`
No need for a change, closing this issue.
